// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9arD_RXKc6Y59RxgIOAYNvfiqpLSGQU',
    appId: '1:138223239701:web:834aa12ee2109185f7041c',
    messagingSenderId: '138223239701',
    projectId: 'ladyrakshak',
    authDomain: 'ladyrakshak.firebaseapp.com',
    storageBucket: 'ladyrakshak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvLhxBbYYMmIhmaGKd_NmyillWjThvEs',
    appId: '1:138223239701:android:36969e6785a393c7f7041c',
    messagingSenderId: '138223239701',
    projectId: 'ladyrakshak',
    storageBucket: 'ladyrakshak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYp25O-66MJxxGQkS9YDkc_E3sVWGVbY',
    appId: '1:138223239701:ios:55e93e48f6eeda26f7041c',
    messagingSenderId: '138223239701',
    projectId: 'ladyrakshak',
    storageBucket: 'ladyrakshak.appspot.com',
    iosClientId: '138223239701-u81fspelhdaurcsfhv9f350km345mirm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladyRakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEYp25O-66MJxxGQkS9YDkc_E3sVWGVbY',
    appId: '1:138223239701:ios:55e93e48f6eeda26f7041c',
    messagingSenderId: '138223239701',
    projectId: 'ladyrakshak',
    storageBucket: 'ladyrakshak.appspot.com',
    iosClientId: '138223239701-u81fspelhdaurcsfhv9f350km345mirm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladyRakshak',
  );
}
